[server]
# Allow external access
headless = true
enableCORS = false
enableXsrfProtection = false

# Bind to all interfaces (0.0.0.0) instead of localhost
address = "0.0.0.0"
port = 8501

# Disable file watcher for production
fileWatcherType = "none"

# Disable browser auto-opening
runOnSave = false

[browser]
# Don't gather usage stats
gatherUsageStats = false

[theme]
# Optional: Set a consistent theme
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
